### DISCUSSION TITLE
feat: Support transparent/dynamic embed color

### DISCUSSION THREAD

**Discussion by KobeW50** [sarisia/actions-status-discord#547] [Ideas, Feature requests]
Discord embeds can have a semi-transparent color that appears different based on the user's theme:

![image](https://github.com/user-attachments/assets/0151da8a-e985-4426-9e30-1c1c99f74f4d)

![image](https://github.com/user-attachments/assets/4fb5ea88-1ec6-4bc5-930f-df7be3207860)

The webhook messages in the images above were generated on discohook.org, which uses this transparent color by default.

According to [this guide](https://birdie0.github.io/discord-webhooks-guide/structure/embed/color.html), an embed's color is transparent by default (set to `0`). 

Similarly, [this doc](https://old.discordjs.dev/#/docs/discord.js/main/typedef/Colors), says that to use the "default" embed color in Discord, the hex code should be `0x000000` or an integer value should be `0`. 

But currently, when using this GitHub action, if the color is set  to `0x000000`, `0`, `0x0`, `0x00000000`, or `000000` the color will end up being green:

![image](https://github.com/user-attachments/assets/c90b53ca-dc7f-45eb-a689-97c158273644)

**Feature**

Add support to specify this transparent embed color.

**Comment by sarisia** [comment]
Wow, I didn't even know `color=0` is valid value...

Let me fix this. Thank you for reporting!

**Comment by sarisia** [comment]
This is released as https://github.com/sarisia/actions-status-discord/releases/tag/v1.14.7, thanks!

**Comment by KobeW50** [comment]
Thank you! Uhh, I am having trouble using it:

I tried `color: 0x000000` and `color: 0` but both led to pure black (not transparent). At least it is not green :)

From the [log](https://github.com/KobeW50/Revancify/actions/runs/10341019722) it seems that it was sent correctly as `0`. (Ignore the `0x000000` in the log. That's just the release tag name.)

So is the default color mentioned in the docs not the transparent one? I am really sorry.

**Comment by KobeW50** [comment]
Update: I asked in the Discohook Discord server, and this is what an admin said

![SmartSelect_20240811_123640_1](https://github.com/user-attachments/assets/15f4469c-2900-43bb-9b84-fbedfd184cf3)

I'm really sorry. I thought it had to be zero.

When trying to specify the color as `color: null` or `color: 'null'`, the result is that the payload will be `"color": 2664261,` (green) instead of `"color": null`.

This is what is seen in the json data editor that the admin mentions:

```
{
  "content": null,
  "embeds": [
    {
      "description": "`\"color\": 0`",
      "color": 0
    },
    {
      "description": "`\"color\": null`",
      "color": null
    }
  ],
  "attachments": []
}
```

**Comment by sarisia** [comment]
Oh, got your point.

I'm not sure what Discohook is but atm we do not have ways to set `color: null`
and since this action aims to easier usage for reporting GitHub Actions result, we have no
plans to support it.

Maybe it's good to have GitHub Actions outputs to expose webhook payload json to latter steps
to help implementing custom solutions, WDYT?

**Comment by KobeW50** [comment]
> Maybe it's good to have GitHub Actions outputs to expose webhook payload json to latter steps
to help implementing custom solutions, WDYT?

Uhh, tbh I don't really understand what this would mean. Is this like being able to fully customize the payload json? If yes, it sounds cool, but only do what makes sense. I do not want you do to anything unreasonable.

**Comment by sarisia** [comment]
Let's say we add the output `payload` to this action, then we can:

```yaml
- uses: actions-status-discord@v1
  id: webhook
- run: npm install axios
- uses: actions/github-script@v7
  env:
    WEBHOOK_PAYLOAD: ${{ steps.webhook.outputs.payload }}
    WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
  with:
    script: |
      const axios = require("axios")
      const { WEBHOOK_PAYLOAD, WEBHOOK_URL } = process.env

      const payload = JSON.parse(WEBHOOK_PAYLOAD)
      payload.embeds[0].color = null

      axios.post(WEBHOOK_URL, payload)
```
