### ISSUE TITLE
Customizable description

### ISSUE THREAD

**Issue by dallin-tranzynergy** [sarisia/actions-status-discord#218]
This workflow currently runs for us to notify of a push to a branch. The description shows the title of that PR, but it would be ideal if we could list the title of each commit included with that PR. Currently looking into what data you are getting back from github and if this is even an option, but figured I would toss it here if anyone knows of a better way to accomplish this. Great action.

**Comment by sarisia** [comment]
We have formatters for common GitHub events implemented in:
https://github.com/sarisia/actions-status-discord/blob/master/src/format.ts

And yes, for pull_request events, we only includes pull request number and title because
we cannot get list of commits from webhook event payload (you can see what you get as event
payload [here](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request) and [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request).

In this case, you can use [actions/github-script](https://github.com/actions/github-script) to
fetch commits & format notification text and then pass it to this action:

> I haven't tested the code below, so be careful!

```yaml
steps:
  - uses: actions/github-script@v5
    id: format_pr
    with:
      script: |
        github.rest.pulls.listCommits({
          context.repo.owner,
          context.repo.repo,
          context.pull_request.number
        })
        // format notification text
        const prDetail = "..."
        core.setOutput("pr_detail", prDetail)
  - uses: sarisia/actions-status-discord@v1
    with:
      nodetail: true
      description: ${{ steps.format_pr.outputs.pr_detail }}
```
