### ISSUE TITLE
feature request: posting into Discord's thread

### ISSUE THREAD

**Issue by KisaragiEffective** [sarisia/actions-status-discord#284]
I would like to post into Discord's thread by this action.
The URL format is `https://discord.com/api/webhooks/{webhook_id}/{webhook.token}?thread_id={thread_id}`.

**Comment by sarisia** [comment]
I think this is out of scope of this action since we do not modify the `webhook` given by user.

If you want to change `thread_id` dynamically, GitHub Actions' [steps context](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) may help:

```yaml
steps:
  - uses: ./some-actions-which-sets-outputs
    id: discord-variables
  - uses: sarisia/actions-status-discord@v1
    with:
      webhook: "https://discord.com/api/webhooks/id_xxx/token_xxx?thread_id=${{steps.discord-variables.outputs.thread-id}}"
```
