### ISSUE TITLE
`nofail` set to `false` does not fail the workflow

### ISSUE THREAD

**Issue by ReenigneArcher** [sarisia/actions-status-discord#562]
**Describe the bug**

`nofail` set to `false` does not fail the workflow when there is no webhook url.

I do get a warning in the logs, but the workflow succeeds. https://github.com/LizardByte/community/actions/runs/12915326548/job/36016941085#step:2:17

**To Reproduce**

```yaml
      - name: discord
        uses: sarisia/actions-status-discord@v1
        with:
          avatar_url: ${{ vars.ORG_LOGO_URL }}256
          color: 0x00ff00  # green
          nodetail: true
          nofail: false
          title: ${{ github.event.issue.title }}
          url: ${{ github.event.issue.body }}
          username: ${{ secrets.DISCORD_USERNAME }}
          webhook: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK }}
```

I moved a workflow from one repo to another, and forgot to enable the secret for the new repo.

**Expected behavior**

Workflow should fail.

**Screenshots**

**Additional context**
